### ISSUE TITLE
startOpenElectrophy must be run in OpenElectrophy dir to load all neo IO?

### ISSUE THREAD

**Issue by lepmik** [OpenElectrophy/OpenElectrophy#11]
I have a wierd bug, I have to run startOpenElectrophy in the git clone dir of OE, if I start it any where else I loose kwikIO and stimfit in Dataset -> Open read only -> IO list

**Comment by samuelgarcia** [comment]
This sound like if you have 2 OpenElectrophy.
One installed in python path and the other on the git clone, if you are in the git clone it use this one if you are outside it use the one in python path which is maybe old and do not manage.
Or this may be the same thing with python-neo.
No more idea. sorry.

**Comment by lepmik** [comment]
well, this turned out to be the latter since I use virtualenv and apparently had installed neo a long time ago vi sudo pip install.. Sorry to flood your issue list..
