### ISSUE TITLE
"std_restrict" not used in function "perform_haar_wavelet"

### ISSUE THREAD

**Issue by amchagas** [OpenElectrophy/OpenElectrophy#12]
Hi, 
I'm not absolutely sure this is a bug (and please forgive me if I'm mistaken), but it seems to me that on the function "perform_haar_wavelet", which is inside /OpenElectrophy/spikesorting/feature/haarwavelet.py, the bit
```python 
 #53 # keep only coeff inside m +- restrict std
 #54       s = np.std(coeffs[:,j], axis=0)*3
```
fixes the the coeffs to 3 SDs, so I guess exchanging the 3 here for "std_restrict" would do the trick?

**Comment by samuelgarcia** [comment]
You are rigth it is a bug.
std_restrict params has not effect because it is hard coded with 3.

I will change it. Unless you do it before with a PR.

**Comment by amchagas** [comment]
Just added the PR.
