### ISSUE TITLE
saving sorted units on one rcg "kills" spike trains on units on other rcgs

### ISSUE THREAD

**Issue by amchagas** [OpenElectrophy/OpenElectrophy#14]
I'm having a bit of a problem when using the GUI for spike sorting:
I load a database (sqlite) that contains 1 block with 1 segment with 12 analogue signals coming from different electrodes. 
Each analog. signal is inside one recording channel (rec) and each rec inside a recording channel group (rcg).

I start spike sorting by script, with thresholding and alignment of waveforms. For this I build 1 unit per rcg (with unit id in the hundreads range. Meaning rcg1 contains unit 100, rcg2 contains unit 200, so that units id numbers won't overlap), containing all spikes inside 1 spike train within this unit (spiketrain id has the same numbering scheme, so that here the id numbers will also not overlap). The next stage is to open the GUI and delete some waveforms (movement artefacts, teeth grinding). After that I run haarwavelets and one of the sorting algorithms. I finalize sorting (do some re-grouping, plot crosscorrelograms) and save the units.    

Once they are saved, something strange happens. Mainly the new units are correctly created with their spike trains. BUT some of the units from other rcgs will loose their spike trains, which makes it impossible to sort them, unless a new group is created. I tried to dig into the save database code to no luck. Any suggestions?

**Comment by samuelgarcia** [comment]
Hi.
Are you taking of the id of the database ?

Normmally you should not choose by yourself the id of an object. It is not in the DB spirit!!!
It leads to lot of errors. You have no garanty that the ID is not already taken.
And teh behavior change from from mysql to sqlite.

SpikeSorter have a method SpikeSorter.save_in_database that do the saving for you.
Maybe this should help you.

**Comment by amchagas** [comment]
Hi Samuel,
Thanks for the help!
I did some testing with what you said (now my scripts do not assign ids to the items in the database), but I still run into the same problem... I had already looked into the SpikeSorter.save_in_database, but I wasn't able to whip something that would get rid of the problem. Also this problem appears mainly when I'm using the GUI, so I'm assuming the GUI will use this method?

You mention: "And teh behavior change from from mysql to sqlite." do you mean that there should be differences when using sqlite and mysql? As in changing the database I'm using, could get rid of the problem?

**Comment by amchagas** [comment]
Hi,
I looked a bit more into this, and I think I spotted where the problem lies... 

My database looks like the following:
1 Block with 1 segment(seg), 5 recordingchannelgroups(rcg).
Inside each rcg one recordingchannel and "n" units. Inside each unit 1 spiketrain (since I only have one segment).

Whenever I use "save" via the spike sorting GUI it runs spikesorter.save_in_database function, as Samuel mentioned earlier. Inside the function, the following code appears:

```python
for u, neounit in enumerate(neorcg.units):
    unit = OEBase.from_neo(neounit, dbinfo.mapped_classes, cascade = False)
    rcg.units.append(unit)
    for s, neoseg in enumerate(neorcg.block.segments):                                
        neosptr = neoseg.spiketrains[u]
        sptr = OEBase.from_neo(neosptr, dbinfo.mapped_classes, cascade = False)
        unit.spiketrains.append(sptr)
        neoseg.OEinstance.spiketrains.append(sptr)
                #~ print 'save',u,  sptr.times.size
```
where neoseg comes from the block and ```neosptr = neoseg.spiketrains[u]``` gets a spike train from neoseg using [u] which is a index for a unit, but units can have more than one spike train, and specially they can come from different segments, so in principle this could lead to getting spike trains in the wrong segment...
I coded a "fix" for it which can be seen below (but it works on the assumption that the spike trains in a unit belong each to one, and only one segment):

```python
        #this is my "fix"
        #run through all units in the neorcg object
        for neoUnit in neorcg.units:
            #print(neoUnit.spiketrains[0].segment)
            #convert each unit and its contained spike trains (cascade = True)
            #to a database object (problem here is that the spiketrains 
            #inside the unit do not have segments, so it has to be manually set)
            unit = OEBase.from_neo(neoUnit, dbinfo.mapped_classes, cascade = True)
            #to manually set the segments, we are going to use the strong 
            #assumption that each unit contains the same number of spike trains
            #as there are segments (ie each segment contains one of the 
            #spike trains from one unit)
            for k in range(0,len(unit.spiketrains)):
                bl.segments[k].spiketrains.append(unit.spiketrains[k])
                unit.spiketrains[k].segment = bl.segments[k]


            #append the unit to the database rcg object
            rcg.units.append(unit)
```

If this is something useful for the project, let me know so I can add a pull request.

**Comment by samuelgarcia** [comment]
Hi,
the code in OpenElectrophy.spikesorting.spikrsorter is
```

**Comment by amchagas** [comment]
Hi Samuel,
Thanks for the reply. It is indeed a mistake on my side. Very sorry about that! What I have on my machine is version 0.3.4, which now I see is not the most up to date one. 

Once again sorry for raising this when it was not correct!

**Comment by amchagas** [comment]
Just a small question, I just removed version 0.3.4 from my machine (ubuntu 14.04, python2.7), and tried to install 0.3.5 with:  
```pip install OpenElectrophy=="0.3.5"  ```

 PIP states that the only available versions are 0.3.1 to 0.3.4 ("pre-0.3.5" also doesn't work). 
I reinstalled version 0.3.4 just to check If I had done something stupid with my previous installation, but the code in  OpenElectrophy.spikesorting.spikesorter is:
```python  
def save_in_database(self, session, dbinfo):
        rcg = self.rcg.OEinstance
        bl = rcg.block
        
        
        for u, unit in enumerate(rcg.units):
            for s, seg in enumerate(bl.segments):
                #~ seg.neoinstance = None
                for sptr in unit.spiketrains:
                    #~ if sptr in seg.spiketrains:
                        #~ seg.spiketrains.remove(sptr)
                    if list_contains(seg.spiketrains, sptr):
                        sptr.neoinstance.OEinstance = None
                        list_remove(seg.spiketrains, sptr)
        for u, unit in enumerate(rcg.units):
            unit.neoinstance.OEinstance = None
            session.delete(unit)
        session.commit()
        #~ bl.neoinstance = None
        
        
        neorcg = self.populate_recordingchannelgroup()
        for u, neounit in enumerate(neorcg.units):
            unit = OEBase.from_neo(neounit, dbinfo.mapped_classes, cascade = False)
            rcg.units.append(unit)
            for s, neoseg in enumerate(neorcg.block.segments):
                neosptr = neoseg.spiketrains[u]
                sptr = OEBase.from_neo(neosptr, dbinfo.mapped_classes, cascade = False)
                unit.spiketrains.append(sptr)
                neoseg.OEinstance.spiketrains.append(sptr)
                #~ print 'save',u,  sptr.times.size
        session.commit()
```
Is this something I'm messing up, or pip doesn't have the latest version, or something else?

**Comment by samuelgarcia** [comment]
OE versions are a total mess.
You should always install from github.
 pip install git+https://github.com/OpenElectrophy/OpenElectrophy.git     

I promiss to release a 0.3.6 soon.
Sorry for this bug.

**Comment by amchagas** [comment]
Hi,
Ok, that is good to know... Maybe, if this is not present yet, one should make a note on the docs?

**Comment by amchagas** [comment]
Sorry to be bugging again, but I have now installed the latest version directly from git with your command above, and I'm getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/OpenElectrophy/gui/qtsqltreeview.py", line 439, in callContextMenu
    m.execute( **kargs)
  File "/usr/local/lib/python2.7/dist-packages/OpenElectrophy/gui/contextmenu.py", line 261, in execute
    spikesorter = SpikeSorter(neo_rcg)
  File "/usr/local/lib/python2.7/dist-packages/OpenElectrophy/spikesorting/spikesorter.py", line 300, in __init__
    self.initialize_from_rcg(rcg)
  File "/usr/local/lib/python2.7/dist-packages/OpenElectrophy/spikesorting/spikesorter.py", line 548, in initialize_from_rcg
    assert sptr is not None
AssertionError
```
This happens when I'm trying to open a database that already has units and spike trains inside the recording channel group. Basically I want to finish sorting on the GUI starting from the waveforms.
Is this a know issue, or something that needs to be looked into?

**Comment by samuelgarcia** [comment]
The reasons of this is : for each Unit/Segment you must have one and only one SpikeTrain. Even if the SpikeTrain is empty (have no spike).
In your case I guess that your Unit do not contain any SpikeTrain. If this is the case : remove manually the Unit in the main treeview.
If this is not that case and if your DB is small could you send me it for a debugging ?

**Comment by amchagas** [comment]
What I have is one Unit per RecordingChannelGroup. Inside this Unit one SpikeTrain (and inside each spike train, times and waveforms from detected and aligned spikes). But inside the one Segment present in the Block, I have all SpikeTrains. 
You can find a example file here (it is a bit large though ~1.5GB) https://www.dropbox.com/sh/3s08r44awfhpefd/AABWa77_13GBvB0jnZhBHtx-a?dl=0

The file contains two recordingchannelgroups. One is the reference channel (which ends up being a channel that never has any spikes, therefore I do not create a unit or spike train inside the RCG). The other is a regular channel, that in this case has one unit, and one spike train inside, with few spikes in it. 

I can open the spikesort GUI for the one that has no spikes in it, but not for the other one (this is when I get the previously mentioned error).

**Comment by samuelgarcia** [comment]
I have your file.
It is a bug.
Sorry for that.
I work on it now.

**Comment by samuelgarcia** [comment]
I have push a patch in the master.
Could you git pull ans try again.

**Comment by amchagas** [comment]
Everything seems to load/save fine now. Thanks for the patch!

**Comment by samuelgarcia** [comment]
Sorry for that. It is due to a recent optimisation that do not load everything but it was bugguy in case of resorting.
