### ISSUE TITLE
Analysis on a part of the HDF5 file

### ISSUE THREAD

**Issue by bastienmaurice** [OpenElectrophy/OpenElectrophy#21]
Hi, 
I have a huge HDF5 file that I created with all the values of a recording. And I would like to do the analysis featured by OpenElectrophy, but only on pieces of this recording.
For example I would like to analyze the sample between 50s and 150s.

For now, I was only able to do that by creating a new HDF5 file for each piece, but I was hoping that there might be a way to read the entire file and then take pieces of it in the code.

So first I read the entire file : 
```
import neo
from OpenElectrophy.spikesorting import (generate_block_for_sorting, SpikeSorter)
r = neo.io.NeoHdf5IO("nerve.h5")
bl = r.read()[0]
rcg = bl.recordingchannelgroups[0]
```

Then I use OpenElectrophy to analyze my data, but I can only apply it on a recordingchannel, and I can't do rcg[50 * sample_rate : 150 * sample_rate]. So I use the spikesorter tool on the entire file :
```
spikesorter = SpikeSorter(rcg)
spikesorter.DerivativeFilter()
spikesorter.ButterworthFilter(f_low = 200)
```

I found that I can reach my data thanks to
`spikesorter.full_band_sigs[0][0][50 * sample_rate : 150 * sample_rate]` or `spikesorter.filtered_sigs[0][0][50 * sample_rate : 150 * sample_rate]` if I want it filtered.

But then I don't know how to do things like that on only a piece of the file : 
`spikesorter.RelativeThresholdDetection(sign = '-', relative_thresh = 6.0)` or `spikesorter.PcaFeature(n_components = 6)` for example.

Thank you for your help.

**Comment by samuelgarcia** [comment]
You need to slice all AnalogSignal in your block bl before spikesorter = SpikeSorter(rcg)
The neo tree is both
Block>Segments>AnalogSignal
Block>RCG>RC>AnalogSignal



Note that this project https://github.com/tridesclous/tridesclous
is more recent taht OE for doing spike sorting, you shoudl also try it.
This is more or less the same approach but easier for data manipulation.
The problem are:
 *  tridesclous is not documented yet, so you need browse codes test and examples.
 * tridesclous is work in progress.

**Comment by bastienmaurice** [comment]
Thank you for your quick answer.

What I did is : 
```
r = neo.io.NeoHdf5IO("nerve.h5")
bl = r.read()[0]
r.close()
seg = bl.segments[0]
asig = seg.analogsignals[0]
sample = asig[1541 * 20000:1549 * 20000]
```
So that is exactly a slice of the analogsignal, then I try to analyze only this part, it shows that it's actually the slice that I want.
```
seg.analogsignals[0] = sample
bl.segments[0] = seg
rcg = bl.recordingchannelgroups[0]
```

 But when I come to the spikesorter, it's processing the entire file, and I don't know why.

```
from OpenElectrophy.spikesorting import (generate_block_for_sorting, SpikeSorter)
spikesorter = SpikeSorter(rcg)
spikesorter.DerivativeFilter()
spikesorter.ButterworthFilter(f_low = 200)
a = spikesorter.full_band_sigs[0][0]
print len(a)
```
And that gives me 87800000 instead of 160000.

I will also take a look at tridesclous, I already have a few codes written with OpenElectrophy that's why I'm trying to slice it to be able to end my analysis. 

Merci pour votre aide et votre travail !

**Comment by samuelgarcia** [comment]
This is because need to be attached both to segment and RC
```
seg = bl.segments[0]
asig = seg.analogsignals[0]
sample = asig[1541 * 20000:1549 * 20000]

seg.analogsignals[0] = sample
#bl.segments[0] = seg # you do not need this
# but ALSO you need this
bl.recordingchannelgroups[0].recordingchannels[0].analogsignals[0] = sample

```

**Comment by bastienmaurice** [comment]
Ok thank you, this works.
Sorry for bothering you with such a small problem, the hierarchical structure is pretty confusing sometimes.

I really thank you for your help.

**Comment by samuelgarcia** [comment]
Yes neo double hierachical structure is really hard to anderstand.
Sorry for that.

tridesclous do not suffer from that.
